version: "3"
services:
  node-express-app: # Name of the container
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db # Using named volumes

# This is make sure mongo-db named volume works without any errors
volumes:
  mongo-db:
