version: "3"
services:
  node-express-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js

  nginx:
    ports: 
      - "80:80"