version: "3"
services:
  node-express-app: # Name of the container
    build: .
    # image: kpunith8/node-app # Required only if you want pull the image from docker hub
    # Ports are required if ngnix is not used as proxy
    # ports:
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db # Using named volumes

  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# This is make sure mongo-db named volume works without any errors
volumes:
  mongo-db:
