version: "3"
services:
  node-express-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - SESSION_SECRET=mysecret
    command: npm run dev

  nginx:
    ports: 
      - "3000:80"